GET = 'GET'
POST = 'POST'
TOKEN = 'token'
PUBKEY = 'pubKey'
CLOSED_GROUP = 'closedGroupPublicKey'
MEMBERS = 'members'
SEND_TO = 'send_to'
DATA = 'data'
CODE = 'code'
MSG = 'message'
STATUS = 'status'
HEADERS = 'headers'
BODY = 'body'
RESULT = 'result'
CIPHERTEXT = 'ciphertext'
EPHEMERAL = 'ephemeral_key'
PARA_MISSING = 'Missing parameter'
SUCCESS = 'Success'
FAIL = 'Fail'

START_DATE = 'start_date'
END_DATE = 'end_date'
IOS_PN_NUMBER = 'ios_pn_number'
IOS_DEVICE_NUMBER = 'ios_device_number'
ANDROID_PN_NUMBER = 'android_pn_number'
ANDROID_DEVICE_NUMBER = 'android_device_number'
TOTAL_MESSAGE_NUMBER = 'total_message_number'
TOTAL_SESSION_ID_NUMBER = 'total_session_id_number'
CLOSED_GROUP_MESSAGE_NUMBER = 'closed_group_message_number'
UNTRACKED_MESSAGE_NUMBER = 'untracked_message_number'
DEDUPLICATED_ONE_ON_ONE_MESSAGE_NUMBER = 'deduplicated_1_1_message_number'

NONCE_LENGTH = 12
TAG_LENGTH = 16

DATABASE_V2 = 'session_pn_server.db'
DATABASE_V2_BACKUP = 'session_pn_server_backup.db'
PUBKEY_TOKEN_TABLE = 'token_pubkey_table'
CLOSED_GROUP_TABLE = 'closed_group_table'
STATISTICS_TABLE = 'statistics_table'
PUBKEY_TOKEN_DB_V2 = 'token_pubkey_db_v2'
CLOSED_GROUP_DB = 'closed_group_db'
CERT_FILE = 'cert.pem'
PRIVKEY_FILE = 'x25519-priv.pem'
FIREBASE_TOKEN = 'loki-5a81e-firebase-adminsdk-7plup-0698317995.json'

BUNDLE_ID = 'com.loki-project.loki-messenger'

debug_mode = True

